# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2167ee8697429bfc2026f0b0aef270e861e69ce513c8153b5e94f13864b41e2a0ada0c177dcdf2beaced39b067d98e91d2461df81778f97f1f45c472689d2f1a

test:
  secret_key_base: 326c6ed9648d87ae8d1666df0aa83e0285d39d141d96eeca3bfb7618129aa048a1843fd470911272968f93e7cd5e8d34ab925cc7abcb5e306ddc9a76353e654a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
